apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: app
commonLabels:
  app: app

images:
  - name: PROF_PAY_SERVER_IMAGE_PLACEHOLDER
    newName: d1mpi/prof-pay-server:1.2.26
    newTag: 1.2.26