apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: prof-pay-server
      namespace: profpay
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: prof-pay-server
        namespace: profpay
      spec:
        template:
          spec:
            imagePullSecrets:
              - name: dockerhub-secret

namespace: profpay
commonLabels:
  app: profpay

images:
  - name: PROF_PAY_SERVER_IMAGE_PLACEHOLDER
    newName: d1mpi/prof-pay-server
    newTag: 1.2.27
  - name: BLOCKCHAIN_IMAGE_PLACEHOLDER
    newName: d1mpi/blockchain-indexer
    newTag: 1.0.10