apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - ../../base

namespace: profpay
commonLabels:
  app: profpay

images:
  - name: IMAGE_PLACEHOLDER
    newName: cr.selcloud.ru/profpay/prof-pay-server
    newTag: 1.2.26