apiVersion: v1
kind: ConfigMap
metadata:
  name: profpay-db-config
  namespace: profpay
data:
  DB_HOST: 111.88.115.81
  DB_PORT: "5432"
  DB_NAME: profpay
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profpay-redis-config
data:
  REDIS_HOST: 111.88.127.230
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profpay-indexer-db-config
  namespace: profpay
data:
  DB_HOST: 45.137.213.192
  DB_PORT: "8123"
  DB_NAME: tron_indexer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profpay-indexer-kafka-config
  namespace: profpay
data:
  KAFKA_HOST: 45.137.213.192
  KAFKA_PORT: "8123"
  KAFKA_APP_ID: default