apiVersion: apps/v1
kind: Deployment
metadata:
  name: prof-pay-server
  namespace: profpay
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: prof-pay-server
  template:
    metadata:
      labels:
        app: prof-pay-server
    spec:
      containers:
        - name: prof-pay-server
          image: PROF_PAY_SERVER_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8284   # HTTP
            - containerPort: 50051  # gRPC
            - containerPort: 8443   # HTTPS
          env:
            - name: JAVA_OPTS
              value: "-Xmx8192m -Xms256m"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                    name: profpay-db-config
                    key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                    name: profpay-db-config
                    key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                    name: profpay-db-config
                    key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                    name: profpay-db-secret
                    key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: profpay-db-secret
                    key: DB_PASSWORD
            
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: profpay-redis-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: profpay-redis-config
                  key: REDIS_PORT

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profpay-redis-secret
                  key: REDIS_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-indexer
  namespace: profpay
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: blockchain-indexer
  template:
    metadata:
      labels:
        app: blockchain-indexer
    spec:
      containers:
        - name: blockchain-indexer
          image: BLOCKCHAIN_IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                    name: profpay-indexer-db-config
                    key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                    name: profpay-indexer-db-config
                    key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                    name: profpay-indexer-db-config
                    key: DB_NAME

            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                    name: profpay-indexer-kafka-config
                    key: KAFKA_HOST

            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                    name: profpay-indexer-kafka-config
                    key: KAFKA_PORT

            - name: KAFKA_APP_ID
              valueFrom:
                configMapKeyRef:
                    name: profpay-indexer-kafka-config
                    key: KAFKA_APP_ID

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                    name: profpay-indexer-db-secret
                    key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: profpay-indexer-db-secret
                    key: DB_PASSWORD