resources:
  - deployment.yaml
  - service.yaml
  - config-map.yaml
  - ingress.yaml
  - persistent-volume-claim.yaml
  - persistent-volume.yaml
  - tls-option.yaml
  - storage.yaml
images:
  - name: IMAGE_PLACEHOLDER
    newName: placeholder
    newTag: placeholder